[package]
name = "mori-bpf-programs"
version = "0.0.1"
edition = "2024"

[dependencies]
aya-ebpf = { version = "0.1.1", default-features = false }
aya-log-ebpf = { version = "0.1.1", default-features = false }

[[bin]]
name = "mori-bpf"
path = "src/main.rs"
