name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/ci.yaml'

  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/ci.yaml'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: rustfmt, clippy
          cache-shared-key: setup-rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install nightly toolchain and bpf tools (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libbpf-dev linux-tools-common linux-tools-$(uname -r)
          rustup toolchain install nightly-x86_64-unknown-linux-gnu --profile minimal --component rust-src
          cargo install bpf-linker bindgen-cli
          cargo install --git https://github.com/aya-rs/aya -- aya-tool

      - name: Install reviewdog
        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0

      - name: Check format
        run: |
          cargo fmt --all -- --check

      - uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: nofilter

      - name: Build
        run: cargo build

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: llvm-tools-preview
          cache-shared-key: setup-rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install nightly toolchain and bpf tools (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libbpf-dev linux-tools-common linux-tools-$(uname -r)
          rustup toolchain install nightly-x86_64-unknown-linux-gnu --profile minimal --component rust-src
          cargo install bpf-linker bindgen-cli
          cargo install --git https://github.com/aya-rs/aya -- aya-tool

      - name: Install tools
        uses: taiki-e/install-action@e7ef886cf8f69c25ecef6bbc2858a42e273496ec # v2.62.28
        with:
          tool: cargo-llvm-cov, cargo-nextest

      - name: Run test
        if: runner.os != 'Linux'
        run: |
          cargo nextest run

      - name: Generate coverage
        if: runner.os == 'Linux'
        run: cargo llvm-cov nextest --lcov --output-path lcov.info

      - name: Upload coverage
        if: runner.os == 'Linux'
        uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run E2E tests
        run: |
          ./tests/e2e/run_tests.sh
